title: "Rancher server documentation"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
logo: "/assets/images/rancher-logo-stacked-color-resize.png"
footer_content: "<button class='btn js-toggle-dark-mode'>Preview dark color scheme</button><script>const toggleDarkMode = document.querySelector('.js-toggle-dark-mode');jtd.addEvent(toggleDarkMode, 'click', function(){if (jtd.getTheme() === 'dark') {jtd.setTheme('light');toggleDarkMode.textContent = 'Preview dark color scheme';} else { jtd.setTheme('dark'); toggleDarkMode.textContent = 'Return to the light side';}});</script></br></br>Copyright &copy; <script>document.write(new Date().getFullYear())</script> Jefferson OC. Distributed by an <a href='https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt'>MIT license.</a>"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
# Supports true (default) or false
heading_anchors: true
nav_sort: case_sensitive # Capital letters sorted before lowercase
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
plugins:
  - jekyll-seo-tag
permalink: pretty
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
sass:
  style: compressed # possible values: nested expanded compact compressed
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
